In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd

In [ ]:
# can also get with uv pip show pandas
pd.__version__

'2.3.2'

In [ ]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv"

df = pd.read_csv(url)

In [6]:
display(df.shape[0])

9704

In [7]:
df.fuel_type.unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [8]:
df.isna().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [12]:
df.origin.unique()

array(['Europe', 'USA', 'Asia'], dtype=object)

In [14]:
df.loc[df.origin == "Asia", "fuel_efficiency_mpg"].max()

np.float64(23.759122836520497)

In [15]:
df.horsepower.median()

np.float64(149.0)

In [16]:
df.horsepower.mode()

0    152.0
Name: horsepower, dtype: float64

In [20]:
df.horsepower = df.horsepower.fillna(df.horsepower.mode().values[0])

In [21]:
df.horsepower.median()

np.float64(152.0)

In [38]:
import numpy as np

X = df.loc[df.origin == "Asia", ["vehicle_weight", "model_year"]].head(7).values

XTX = np.dot(X.T, X)
display(XTX)

array([[62248334.33150761, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [37]:
invxtx = np.linalg.inv(XTX)
invxtx

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [49]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]
w = np.dot(invxtx, X.T)
w = np.dot(w, y)
w

array([0.01386421, 0.5049067 ])

In [50]:
w.sum()

np.float64(0.5187709081074006)